Selhosa\ElectronicBundle\Entity\BrandFamily:
    type: entity
    table: Electronic
    indexes:
        reference_IDX_1:
          columns: [ model ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: '40'
        description:
            type: string
            length: '255'
    oneToMany:
        models:
            targetEntity: Electronic
            mappedBy: brandFamily
            cascade: ["all"]
    manyToOne:
        brand:
            targetEntity: Brand
            inversedBy: electronicFamilies
            joinColumn:
                name: brand_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
