Selhosa\ElectronicBundle\Entity\ElectronicCategory:
    type: entity
    table: ElectronicCategory
    repositoryClass: Selhosa\ElectronicBundle\Repository\ElectronicCategoryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: '40'
        description:
            type: string
            length: '255'
    oneToMany:
        electroncis:
            targetEntity: Electronic
            mappedBy: category
            cascade: ["all"]
    oneToMany:
        interventions:
            targetEntity: Selhosa\RepairBundle\Entity\ElectronicCategoryIntervention
            mappedBy: electronicCategory
            cascade: ["all"]
    manyToOne:
        brand:
            targetEntity: Brand
            inversedBy: electronicCategories
            joinColumn:
                name: brand_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
