Selhosa\ElectronicBundle\Entity\Electronic:
    type: entity
    table: Electronic
    repositoryClass: Selhosa\ElectronicBundle\Repository\ElectronicRepository
    indexes:
        reference_IDX_1:
          columns: [ model ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        model:
            type: string
            length: '40'
            column: model
    oneToMany:
        repairs:
            targetEntity: Selhosa\RepairBundle\Entity\Repair
            mappedBy: electronic
            cascade: ["all"]
    manyToOne:
        category:
            targetEntity: ElectronicCategory
            inversedBy: electronics
            joinColumn:
                name: electronic_category_id
                referencedColumnName: id
                nullable: true
    lifecycleCallbacks: {  }
