selhosa_reparation_homepage:
    pattern:  /
    defaults: { _controller: SelhosaReparationBundle:Crud:index }
selhosa_reparation_list:
    pattern:  /ordres-treball/{statusKeyword}
    defaults: { _controller: SelhosaReparationBundle:Crud:index }
selhosa_reparation_create:
    pattern:  /entrar-ot
    defaults: { _controller: SelhosaReparationBundle:Crud:create }
selhosa_reparation_update:
    pattern:  /editar-ot/{id}
    defaults: { _controller: SelhosaReparationBundle:Crud:update }
selhosa_reparation_change_status:
    pattern:  /ajax/canviar-estat-ot
    defaults: { _controller: SelhosaReparationBundle:WorkFlow:changeStatus }
