parameters:
#    selhosa_reparation.example.class: Selhosa\ReparationBundle\Example

services:
#    selhosa_reparation.example:
#        class: %selhosa_reparation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]services: