parameters:
#    selhosa_electronic.example.class: Selhosa\ElectronicBundle\Example

services:
  selhosa.electronic.creator:
    class: Selhosa\ElectronicBundle\Creator\ElectronicCreator
    arguments: [@doctrine.orm.entity_manager]