<?php

namespace Selhosa\WorkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkOrderRepository extends EntityRepository
{
}
