Selhosa\RepairBundle\Entity\Charges:
    type: entity
    table: Charges
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        realWorkedTime:
            type: integer
            nullable: true
        chargebleTime:
            type: integer
            nullable: true
    manyToOne:
        repair:
            targetEntity: Repair
            inversedBy: charges
            joinColumn:
                name: repair_id
                referencedColumnName: id
                nullable: false
            cascade: ['persist']
        intervention:
            targetEntity: Intervention
            joinColumn:
                name: intervention_id
                referencedColumnName: id
                nullable: true
            cascade: ['persist']
    lifecycleCallbacks: {  }