Selhosa\RepairBundle\Entity\Intervention:
    type: entity
    table: Intervention
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: '10'
        description:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
