Selhosa\RepairBundle\Entity\Repair:
    type: entity
    table: Repair
    repositoryClass: Selhosa\RepairBundle\Repository\RepairRepository
    fields:

    manyToOne:
        electronic:
            targetEntity: Selhosa\ElectronicBundle\Entity\Electronic
            inversedBy: repairs
            joinColumn:
                name: electronic_id
                referencedColumnName: id
                nullable: true
            cascade: ['persist']
    oneToMany:
        charges:
            targetEntity: Selhosa\RepairBundle\Entity\Charges
            mappedBy: repair
            cascade: ["all"]
    lifecycleCallbacks: {  }