Selhosa\ReparationBundle\Entity\DaoWorkOrder:
    type: entity
    table: DaoWorkOrder
    repositoryClass: Selhosa\ReparationBundle\Entity\DaoWorkOrderRepository
    fields:
    lifecycleCallbacks: {  }