Selhosa\ReparationBundle\Entity\WorkOrderStatus:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        description:
            type: string
            length: '70'
        keyword:
            type: string
            length: '30'
    oneToMany:
        workorders:
            targetEntity: WorkOrder
            mappedBy: status
    lifecycleCallbacks: {  }
