Selhosa\ReparationBundle\Entity\WorkOrder:
    type: entity
    table: WorkOrder
    inheritanceType: JOINED
    discriminatorColumn:
        name: workorder_type
        type: string
        length: null
    discriminatorMap:
        workorder: Selhosa\ReparationBundle\Entity\WorkOrder
        daoworkorder: Selhosa\ReparationBundle\Entity\DaoWorkOrder
    repositoryClass: Selhosa\ReparationBundle\Entity\WorkOrderRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        reference:
            type: string
            length: '20'
        model:
            type: string
            length: '50'
        priority:
            type: boolean
    oneToMany:
        notes:
            targetEntity: Note
            mappedBy: workorder
    lifecycleCallbacks: {  }
