Selhosa\WorkBundle\Entity\Note:
    type: entity
    table: Note
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                  on: create
        comment:
            type: text
    manyToOne:
        workorder:
            targetEntity: WorkOrder
            inversedBy: notes
            joinColumn:
                name: workorder_id
                referencedColumnName: id
                nullable: false
            cascade: ['persist']
    lifecycleCallbacks: {  }
