Selhosa\UserBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: Selhosa\UserBundle\Repository\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
      groups:
        targetEntity: Group
        joinTable:
          name: User_Groups
          joinColumns:
            user_id:
             referencedColumnName: id
          inverseJoinColumns:
            group_id:
              referencedColumnName: id
      workorders:
          targetEntity: Selhosa\WorkBundle\Entity\WorkOrder
          mappedBy: technicians
    lifecycleCallbacks: {  }
